main: com.alpsbte.bungee.BungeePlugin
version: 1.2
api-version: 1.12.2
name: AlpsBTE-Bungee
author: R3tuxn

commands:
  yeet:
    description: yeet a player
    usage: /yeet <player>
    permission: alpsbte.yeet
  ping:
    description: get your ping to the proxy
    usage: /ping
    permission: alpsbte.ping
  discord:
    description: get a link to our Discord server
    usage: /discord
    permission: alpsbte.discord
  re:
    description: quick rejoin
    usage: /re
    permission: alpsbte.rejoin
  addbuilder:
    description: add builder permissions to player
    usage: /addbuilder <Name/UUID>
    permission: alpsbte.reviewer
  removebuilder:
    description: remove builder permissions from player
    usage: /removebuilder <Name/UUID>
    permission: alpsbte.reviewer